default_meta: []
default_status: proposed
directory: .
id_digit_number: 4
supported_statuses:
    - proposed
    - accepted
    - rejected
    - superseded
    - amended
    - deprecated
template_file: adr_template.md
